#!/usr/bin/env perl
use strict;
use warnings;
use Perl::Critic;
if (!defined $ARGV[0])
{
  print "usage: $0 <file>\n";
  exit 0;
}

if (!-e $ARGV[0])
{
  print "$0: could not find $ARGV[0]\n";
  print "usage: $0 <file>\n";
  exit 0;
}

my $critic = Perl::Critic->new();
my @violations = $critic->critique($ARGV[0]);

if (!defined $violations[0])
{
  print "$ARGV[0] passed (no violations)\n";
  exit 0;
}

print "Violations:\n";
print "$_\n" foreach (@violations);
